[package]
name = "kdam-c-bindings"
version = "0.0.1-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kdam = "0.3.0"

[lib]
crate-type = ["staticlib"]
